"""Generate the in-page annotated extraction JS from schema/ui_taxonomy.yaml.

Single source of truth: taxonomy yaml → selectors injected into JS template.
Output: scripts/js/extract_annotated.js  (page-context () => {...})
"""
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

JS_TEMPLATE = """() => {
  // auto-generated by collector/build_extract_js.py from schema/ui_taxonomy.yaml
  const RULES = __RULES__;
  function visibleRect(el) {
    if (!el || el.nodeType !== Node.ELEMENT_NODE) return null;
    if (el.hidden) return null;
    if (el.getAttribute('aria-hidden') === 'true') return null;
    const s = getComputedStyle(el);
    if (s.display === 'none' || s.visibility === 'hidden' || s.visibility === 'collapse') return null;
    if (parseFloat(s.opacity) === 0) return null;
    const r = el.getBoundingClientRect();
    if (r.width < 1 || r.height < 1) return null;
    if (r.right < 0 || r.bottom < 0 || r.left > innerWidth || r.top > innerHeight) return null;
    return r;
  }
  function stateOf(el) {
    return {
      expanded: el.getAttribute('aria-expanded'),
      pressed: el.getAttribute('aria-pressed'),
      selected: el.getAttribute('aria-selected'),
      checked: el.getAttribute('aria-checked'),
      disabled: el.disabled === true || el.getAttribute('aria-disabled') === 'true',
    };
  }
  const seen = new Set();
  const out = [];
  for (const rule of RULES) {
    let els = [];
    try { els = Array.from(document.querySelectorAll(rule.sel)); } catch (e) {}
    for (const el of els) {
      if (seen.has(el)) continue;
      const r = visibleRect(el);
      if (!r) continue;
      seen.add(el);
      out.push({
        _el: el,
        role: rule.role,
        source: rule.source,
        testid: el.getAttribute('data-testid'),
        aria: (el.getAttribute('aria-label') || '').slice(0, 100) || null,
        text: (el.innerText || '').replace(/\\s+/g, ' ').trim().slice(0, 120) || null,
        tag: el.tagName.toLowerCase(),
        rect: { x: +r.x.toFixed(1), y: +r.y.toFixed(1), w: +r.width.toFixed(1), h: +r.height.toFixed(1) },
        z: Number(getComputedStyle(el).zIndex) || 0,
        ...stateOf(el),
      });
    }
  }
  // icon_button fallback: small aria-labelled buttons not already captured
  for (const el of document.querySelectorAll('button[aria-label]')) {
    if (seen.has(el)) continue;
    const r = visibleRect(el);
    if (!r || r.width > 64 || r.height > 64) continue;
    seen.add(el);
    out.push({
      _el: el,
      role: 'icon_button', source: 'heuristic',
      testid: el.getAttribute('data-testid'),
      aria: (el.getAttribute('aria-label') || '').slice(0, 100),
      text: null, tag: 'button',
      rect: { x: +r.x.toFixed(1), y: +r.y.toFixed(1), w: +r.width.toFixed(1), h: +r.height.toFixed(1) },
      z: 0, ...stateOf(el),
    });
  }
  // login-state heuristics (onboarding/login routes only): inputs + continue/oauth buttons
  if (/login|onboarding|signup|flow/i.test(location.pathname + location.search)) {
    for (const el of document.querySelectorAll("input[autocomplete*='username'], input[type='password'], input[autocomplete*='email'], input[name='text'][inputmode='email']")) {
      if (seen.has(el)) continue;
      const r = visibleRect(el);
      if (!r) continue;
      seen.add(el);
      out.push({ _el: el, role: 'login_input', source: 'dom-heuristic', testid: null,
        aria: el.getAttribute('aria-label'), text: null, tag: 'input',
        rect: { x: +r.x.toFixed(1), y: +r.y.toFixed(1), w: +r.width.toFixed(1), h: +r.height.toFixed(1) },
        z: 0, ...stateOf(el) });
    }
    const CONT = /^(继续|下一步|登录|注册|continue|next|log ?in|sign ?in)/i;
    const OAUTH = /(google|apple|手机|phone)/i;
    for (const el of document.querySelectorAll("button, [role='button']")) {
      if (seen.has(el)) continue;
      const t = (el.innerText || '').trim();
      if (!t) continue;
      const r = visibleRect(el);
      if (!r) continue;
      if (CONT.test(t) || (OAUTH.test(t) && /继续|continue/i.test(t))) {
        seen.add(el);
        out.push({ _el: el, role: 'login_button', source: 'text-heuristic', testid: null,
          aria: el.getAttribute('aria-label'), text: t.slice(0, 60), tag: el.tagName.toLowerCase(),
          rect: { x: +r.x.toFixed(1), y: +r.y.toFixed(1), w: +r.width.toFixed(1), h: +r.height.toFixed(1) },
          z: 0, ...stateOf(el) });
      }
    }
  }
  return {
    url: location.href, vw: innerWidth, vh: innerHeight, dpr: devicePixelRatio,
    scrollY: window.scrollY, theme_bg: getComputedStyle(document.body).backgroundColor,
    dark: matchMedia('(prefers-color-scheme: dark)').matches,
    n: out.length, els: out,
    // v2 additions ------------------------------------------------
    // hierarchy: parent index among captured elements (visible-ancestor walk)
    hierarchy: (() => {
      const idx = new Map();
      out.forEach((e, i) => idx.set(e._el, i));
      const h = [];
      for (const e of out) {
        let p = e._el && e._el.parentElement, pi = null;
        while (p) {
          if (idx.has(p)) { pi = idx.get(p); break; }
          p = p.parentElement;
        }
        h.push(pi);
        delete e._el;
      }
      return h;
    })(),
    // text spans: per-line text boxes via Range.getClientRects (Webshot-style)
    text_spans: (() => {
      const res = [];
      const walker = document.createTreeWalker(document, NodeFilter.SHOW_TEXT);
      let n = walker.nextNode(), guard = 0;
      while (n && res.length < 400 && guard++ < 4000) {
        const s = (n.nodeValue || '').replace(/\\s+/g, ' ').trim();
        if (s.length < 1) { n = walker.nextNode(); continue; }
        const range = document.createRange();
        range.selectNodeContents(n);
        for (const r of Array.from(range.getClientRects()).slice(0, 6)) {
          if (r.width < 2 || r.height < 2) continue;
          if (r.top > innerHeight || r.bottom < 0) continue;
          const parent = n.parentElement;
          const cs = parent ? getComputedStyle(parent) : null;
          if (cs && (cs.visibility === 'hidden' || cs.display === 'none')) break;
          res.push({ text: s.slice(0, 100),
            rect: { x: +r.x.toFixed(1), y: +r.y.toFixed(1), w: +r.width.toFixed(1), h: +r.height.toFixed(1) },
            fs: cs ? Math.round(parseFloat(cs.fontSize)) : null });
          break; // first rect per node ≈ the line box
        }
        n = walker.nextNode();
      }
      res.sort((a, b) => a.rect.y - b.rect.y || a.rect.x - b.rect.x);
      return res;
    })(),
  };
}
"""


def main() -> None:
    tax = yaml.safe_load((ROOT / "schema/ui_taxonomy.yaml").read_text())
    rules = []
    for role, spec in tax["classes"].items():
        dom = spec.get("dom", "")
        if not dom or "（" in dom:  # heuristic-only classes handled in JS
            continue
        # strip quote wrappers: dom strings contain CSS selectors already
        sel = dom.strip().strip('"')
        if not sel or "（未匹配" in sel:
            continue
        # multi-selector strings like "a, b" are fine for querySelectorAll
        source = "dom-testid" if "data-testid" in sel else "dom-aria"
        rules.append({"role": role, "sel": sel, "source": source})
    import json

    js = JS_TEMPLATE.replace("__RULES__", json.dumps(rules, ensure_ascii=False))
    out = ROOT / "scripts/js/extract_annotated.js"
    out.write_text(js)
    print(f"{len(rules)} rules → {out}")
    for r in rules:
        print(f"  {r['role']:20s} {r['sel'][:70]}")


if __name__ == "__main__":
    main()
